### ISSUE TITLE
Any documentation on how to use this tool ?

### ISSUE THREAD

**Issue by AkechiShiro** [ANSSI-FR/ORADAD#10]
Hi, 

I did not find any documentation linked, beside the config file is there any documentation online readable besides the source code of this tool ?

If so, could they be linked in the README please, just showing how to launch the tool is great but not enough, I believe, as the configuration isn't documented in a website.

If I find anything, I'll drop a PR.

**Comment by jbgalet** [comment]
This tool is designed to be used with the ANSSI ADS service (for french public entities and regulated companies) and is published as open-source for transparency.

It is a LDAP / Sysvol data collector you run with `ORADAD.exe <outputDirectory>` (cf. README). You can find additional settings in [config-oradad.xml](https://github.com/ANSSI-FR/ORADAD/blob/master/config-oradad.xml).
