### ISSUE TITLE
Privileged users revealed on RODC - vuln_rodc_priv_revealed - Why is it based on msDS-RevealedDSAs instead of msDS-RevealedList ?

### ISSUE THREAD

**Issue by manupfpc** [ANSSI-FR/ORADAD#11]
Hello,
I have an issue with the following check: Privileged users revealed on RODC - vuln_rodc_priv_revealed. It seems it is based on the AD attribute **msDS-RevealedDSAs**. Not sure this attribute is the most relevant. I explain: This attribute will keep the information even if the password has rotated and is not cached on the RODC anymore. Use case: I install an RODC. I join the server to the AD domain therefore the password of my server is cached by the nearest DC (which is an RODC). Then I promote my server to become an RODC too. At the end, the attribute msDS-RevealedDSAs will keep the information forever whereas it is not in cache anymore because it became an RODC and it's computer account is member of the group "Denied RODC Password Group".

I think it would be more relevant to check the attribute: **msDSRevealedList**. This attribute keeps up to date the list of currently cached accounts. This command get the list of currently cached password accounts : **Repadmin.exe /prp view <RODCServerName> reveal**
Do ou think it could be implemented in the next release or ORADAD to replace the current check?
Thanks for reading.

**Comment by jbgalet** [comment]
Hello,
The list is based on the `msDS-RevealedUsers` attribute (`msDS-RevealedList` is built from it). 
Promoting a RODC from an existing RODC network looks like a corner case not handled by the ADS analyzers.

Computer account passwords revealed on RODC could be safely ignored when the passwords is changed (not affected by human pattern behaviors) using the same pseudo code as `msDS-RevealedList`

This is however an issue for ADS (analysis) that you should send to your contact at ANSSI and not on this repository (ORADAD dumper)

**Comment by manupfpc** [comment]
Hello, Many thanks for your explanation.
