### ISSUE TITLE
[vuln1_spn_priv]	

### ISSUE THREAD

**Issue by AlphonseBa** [ANSSI-FR/ORADAD#13]
Hello, I have a problem concerning the vuln1_spn_priv vulnerability. The AGPM administrator account with its spn must have backup operator rights.
oradad recommends the following to solve the problem 
"
a refined password policy (Password Settings Object or PSO) is applied to the account with a password length greater than 32 ;
a refined password policy (Password Settings Object or PSO) is applied to the account, with a maximum expiry time of 3 years;
the account password has changed since the last PSO modification;
the account can only use AES algorithms.
"
I've implemented this process, but the vulnerability is still present.

Does the oradad check that the PSO is correctly applied to the account, as well as the other parameters? 

This prevents me from going to level 2.

Thanks in advance

**Comment by jbgalet** [comment]
Hello,
PSO usually cannot be read by standard users, to have them checked by ADS you have to run ORADAD with an account that have READ access to PSOs.
In the report, an information point should list PSO settings, if it is not present, empty or not displaying the details then the required data is not available.

**Comment by AlphonseBa** [comment]
Thank you ! :) 
In the guide we can read that the user who run the oradad doesn't need specific priviledge.

But it's fix  now! And level 2 is here. 
Thank you @jbgalet  :)
