### ISSUE TITLE
Intérêt à lancer ORADAD en tant qu'administrateur du domaine ?

### ISSUE THREAD

**Issue by chulpea** [ANSSI-FR/ORADAD#17]
Bonjour,

Est-ce qu'il y a un intérêt à lancer l'outil ORADAD en tant qu'administrateur du domaine ?

Bonne journée à vous.

**Comment by jbgalet** [comment]
Bonjour,

Lancer ORADAD avec un compte à hauts privilèges permet de relever certains objets qui sont normalement inaccessibles aux utilisateurs standard, par exemple les PSO (utilisées par ADS pour évaluer certaines mitigations) ou certaines GPO.

**Comment by chulpea** [comment]
C'est noté, merci pour la réponse.
