### ISSUE TITLE
dumping 'passwordSettings’ failed

### ISSUE THREAD

**Issue by DannyPans** [ANSSI-FR/ORADAD#3]
I ran ORADAD v2.8.152 on a forest with 70 domains and Enterprise admin rights.
After processing 8 domains successfully, it stopped on 9th domain dumping 'passwordSettings’.
I checked all the PSOs of that domain. I can open them without any issue.

I also tried ORADAD v2.6.130, same issue: dumping 'passwordSettings’ not finished on same domain.

Any help is welcome.

**Comment by moreauleonard** [comment]
Hi,

Have you still an access to the domain that fail to dump data ?
Launching Oradad, only on this domain also fail ?

Can you provide logs/CLI output ?

**Comment by DannyPans** [comment]
Hi,

5 domains in forest: LTES.local; LD01.LTES.local; LD02.LTES.local; LD03.LTES.local; LD04.LTES.local


  1.  Launch ORADAD in LTES.local: LD02 OK; LD03 failed; LD01/LD04 not started          -> oradad_LTES_1.log
  2.  Launch ORADAD in LTES.local (autoGetTrusts disabled): LTES failed          -> oradad_LTES_2.log
  3.  Launch ORADAD in LD03.LTES.local: LTES failed; LD01/LD02/LD03/LD04 not started          -> oradad_LD03_1.log
  4.  Launch ORADAD in LD03.LTES.local (autoGetTrusts disabled): LD03 failed         -> oradad_LD03_2.log

**Comment by jbgalet** [comment]
Hi,

If you don't get an error message in the oradad.log file there are chances that it's a crash. I'd be interested by the associated crash dump or stack trace (look in WER folders).

**Comment by DannyPans** [comment]
Hi,

Last lines in the oradad.log file are:

2020/11/24 - 00:04:55.006 4        LDAP.cpp      LdapProcessRequest 444     [.] Dumping 'xxx.local/domain/Dxx.xxx.local/packageRegistration'.
2020/11/24 - 00:04:55.006 5        LDAP.cpp      pLdapOpenConnection         1349   [+] Successfully bind to XSxxxxxx.Dxx.xxx.local.
2020/11/24 - 00:04:55.069 4        LDAP.cpp      LdapProcessRequest 1209      [+] Finished: elapsed time: 0 second, 0 object.
2020/11/24 - 00:04:55.069 4        LDAP.cpp      LdapProcessRequest 444     [.] Dumping 'xxx.local/domain/Dxx.xxx.local/passwordSettings'.
2020/11/24 - 00:04:55.084 5        LDAP.cpp      pLdapOpenConnection         1349   [+] Successfully bind to XSxxxxxx.Dxx.xxx.local.

No folder/files in WER\ReportArchive or WER\ReportQueue found.

**Comment by jbgalet** [comment]
The new release (2.9.160) fixes this issue. Thanks for your help.

**Comment by BureauAudit** [comment]
Bug corrected in de12fb1.
