### ISSUE TITLE
rule L1 "Accounts with adminCount attribute": false positive in analysis report

### ISSUE THREAD

**Issue by DannyPans** [ANSSI-FR/ORADAD#4]
rule L1 "Accounts with adminCount attribute" does not take into account nested groups.

Example: account (adminCount=1) member of group (adminCount=1) member of DNSAdmins (adminCount=1)   => false positive in ANSSI
Why: this account belongs to privileged group (via group nesting), which are protected by the adminSDHolder mechanism, so this account is a privileged account and should have adminCount=1

**Comment by jbgalet** [comment]
Hi,

Is this issue about ORADAD or the ADS reports provided by ANSSI?
For the latest please send an email to your ANSSI contact.

**Comment by DannyPans** [comment]
This issue is about ADS report provided by ANSSI. I will mail my ANSSI contact.
