### ISSUE TITLE
Erreur processing sysvol : unable to find files

### ISSUE THREAD

**Issue by arnaudminvielle** [ANSSI-FR/ORADAD#6]
Bonjour,
  lors de l’exécution, une fois arrivé à la partie 
[.] Processing sysvol: '\\[monDC].[monDomain]\SYSVOL'
j'ai une erreur 
[!] Unable to find files (path '\\[monDC].[monDomain]\SYSVOL\[monDomain]\DfsrPrivate\*', error 5).
[!] Cannot open sysvol file '' (error 3).
[!] Cannot get file attributes for '' (error 3).

(Rq : les valeurs de monDC et monDomain sont bien correctes)

Au bout d'un moment, il semble que l’exécution prenne fin
[.] Write table info.
[.] End.
Mais cette erreur est-elle gênante pour l'analyse future du dump ?

Le répertoire \\[monDC].[monDomain]\SYSVOL\[monDomain]\DfsrPrivate\ existe bien, mais un simple compte utilisateur du domaine sur un pc du domaine n'y a pas accès (d'où l'erreur certainement).

Merci d'avance pour vos lumières,
Arnaud

**Comment by jbgalet** [comment]
Bonjour,

C'est normal que certains fichiers du sysvol ne puissent pas être lus, ce n'est pas grave pour l'analyse du moment que ORADAD arrive au bout (message End).
