### ISSUE TITLE
Unable locate DC for domain 1355 Unable to open ldap connexion error 81 serveur hors service"

### ISSUE THREAD

**Issue by TLD18000** [ANSSI-FR/ORADAD#7]
Bonjour,

j'ai utilisé ORADAD sur client et serveur réseau isolé W7SP1 avec plusieurs profils j'ai toujours le même retour.

"Unable locate DC for domain 1355

Unable to open ldap connexion error 81 serveur hors service"

En vous remerciant par avance pour vos lumières,

Bien cordialement.

**Comment by m33m33** [comment]
> "Unable locate DC for domain 1355
> 
> Unable to open ldap connexion error 81 serveur hors service"

Bonjour,
perso j'ai résolu ça en passant autoGetDomain à zéro,
et rensigné une section domain avec un nom de DC et un compte utilisateur (non privilégié) + domaine + mdp.
Cdt
